[toolchain]
channel = "stable"
anchor_version = "0.32.1"

[workspace]
resolver = "2"

[features]
skip-lint = false

[programs.localnet]
civic_streak = "AcwHoN69JyVtJ9S82YbkJaW3Xd1eksUKCgRCfftc8A7X"

[programs.devnet]
civic_streak = "AcwHoN69JyVtJ9S82YbkJaW3Xd1eksUKCgRCfftc8A7X"

[programs.testnet]
civic_streak = "AcwHoN69JyVtJ9S82YbkJaW3Xd1eksUKCgRCfftc8A7X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/prashanna/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
