[toolchain]
channel = "stable"
anchor_version = "0.32.1"

[workspace]
resolver = "2"

[features]
skip-lint = false

[programs.localnet]
civic_streak = "AZk4djCf76yJ5qEfJgu3muTtYmW6Wm7bL8Bsjsj1MMGu"

[programs.devnet]
civic_streak = "AZk4djCf76yJ5qEfJgu3muTtYmW6Wm7bL8Bsjsj1MMGu"

[programs.testnet]
civic_streak = "AZk4djCf76yJ5qEfJgu3muTtYmW6Wm7bL8Bsjsj1MMGu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
