[toolchain]
channel = "stable"
anchor_version = "0.32.1"

[workspace]
resolver = "2"

[features]
skip-lint = false

[programs.localnet]
civic_streak = "ChNrscvcMYLVxwcrS1ukyGTXZ16U7VZ71Vv573Ue6W6s"

[programs.devnet]
civic_streak = "ChNrscvcMYLVxwcrS1ukyGTXZ16U7VZ71Vv573Ue6W6s"

[programs.testnet]
civic_streak = "ChNrscvcMYLVxwcrS1ukyGTXZ16U7VZ71Vv573Ue6W6s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
